name: Build the Kernel and package it
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Free up disk space for the CI
        run: |
          df -h
          echo "==> Cleaning up disk space for the CI..."
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          df -h
    
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Build in Docker
        run: |
          cat << EOF > dockerBuild.sh
          cd /build
          useradd builduser -m
          passwd -d builduser
          emerge --sync
          emerge --verbose --update --deep --newuse @world
          USE=zstd emerge sys-apps/kmod 
          emerge dev-util/pahole app-admin/sudo dev-vcs/git net-misc/curl dev-lang/perl sys-devel/bc app-arch/cpio
          printf 'builduser ALL=(ALL) ALL\\n' | tee -a /etc/sudoers
          chown -R builduser:builduser ./
          sudo -u builduser gpg --keyserver keyserver.ubuntu.com --recv-keys 38DBBDC86092693E
          sudo -u builduser bash -c "chmod +x prepare.sh && chmod +x build.sh && chmod +x package.sh"
          sudo -u builduser bash -c "./prepare.sh && ./build.sh && ./package.sh"
          EOF
          
          docker run -t -v $PWD:/build gentoo/stage3 /bin/bash /build/dockerBuild.sh
          
      - name: Upload Packages
        uses: actions/upload-artifact@v2
        with:
          name: built-packages
          path: ${{ github.workspace }}/linux-t2-*.tar.xz
          
      # TODO: if CI is confirmed to work, then create a tag and make a release with the artifacts
